name: Build Ubuntu 22.04

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Display Ubuntu version
        run: lsb_release -a
      - name: Make script executable
        run: chmod +x ci/build_ubuntu.sh
      - name: Run build script
        run: sh ci/build_ubuntu.sh
