name: Build Windows

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge,defaults
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install conda-forge::xerces-c
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.9.*'
      - name: Build
        run: ci\build_windows.bat
